### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by whatsinthedev** [gitmaxcode/rocktuberewritten#1]
- [ ] Password reset/change
- [ ] Username change
- [ ] Logout
- [ ] Studio
- [ ] New UI
- [ ] Better name
- [ ] Image and video support
- [ ] Profile pictures and banners

**Comment by whatsinthedev** [comment]
very epic yee new ui and name

**Comment by jko64** [comment]
fuck bootstrap

**Comment by jko64** [comment]
Nevermind my previous comment lo
